<template>
  <el-row class="mb-4">
    <div class="sketchfab-embed-wrapper"> <iframe title="Double pipe heat exchanger" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="640" height="480" src="https://sketchfab.com/models/18c46f8864814f19993e32fac30c9cd2/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/double-pipe-heat-exchanger-18c46f8864814f19993e32fac30c9cd2?utm_medium=embed&utm_campaign=share-popup&utm_content=18c46f8864814f19993e32fac30c9cd2" target="_blank" style="font-weight: bold; color: #1CAAD9;"> Double pipe heat exchanger </a> by <a href="https://sketchfab.com/3d.atoa?utm_medium=embed&utm_campaign=share-popup&utm_content=18c46f8864814f19993e32fac30c9cd2" target="_blank" style="font-weight: bold; color: #1CAAD9;"> 3DPrinting.atoa </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=18c46f8864814f19993e32fac30c9cd2" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>
    <div class="sketchfab-embed-wrapper"> <iframe title="Finned Tube Heat Exchanger" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share  width="640" height="480" src="https://sketchfab.com/models/d05feb0ea1ab49e5a8f3ea89898e0eaa/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/finned-tube-heat-exchanger-d05feb0ea1ab49e5a8f3ea89898e0eaa?utm_medium=embed&utm_campaign=share-popup&utm_content=d05feb0ea1ab49e5a8f3ea89898e0eaa" target="_blank" style="font-weight: bold; color: #1CAAD9;"> Finned Tube Heat Exchanger </a> by <a href="https://sketchfab.com/3d.atoa?utm_medium=embed&utm_campaign=share-popup&utm_content=d05feb0ea1ab49e5a8f3ea89898e0eaa" target="_blank" style="font-weight: bold; color: #1CAAD9;"> 3DPrinting.atoa </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=d05feb0ea1ab49e5a8f3ea89898e0eaa" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>
    <div class="sketchfab-embed-wrapper"> <iframe title="Heat Exchanger" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="640" height="480" src="https://sketchfab.com/models/d16dc8d787594e6d82fefde9d02aebcf/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/heat-exchanger-d16dc8d787594e6d82fefde9d02aebcf?utm_medium=embed&utm_campaign=share-popup&utm_content=d16dc8d787594e6d82fefde9d02aebcf" target="_blank" style="font-weight: bold; color: #1CAAD9;"> Heat Exchanger </a> by <a href="https://sketchfab.com/DigitalTwinStudios?utm_medium=embed&utm_campaign=share-popup&utm_content=d16dc8d787594e6d82fefde9d02aebcf" target="_blank" style="font-weight: bold; color: #1CAAD9;"> Digital Twin Studios </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=d16dc8d787594e6d82fefde9d02aebcf" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>
    <div class="sketchfab-embed-wrapper"> <iframe title="Shell and Tube Heat Exchanger" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="640" height="480" src="https://sketchfab.com/models/2551fb0c60d543edbcc09c97bcacdaca/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/shell-and-tube-heat-exchanger-2551fb0c60d543edbcc09c97bcacdaca?utm_medium=embed&utm_campaign=share-popup&utm_content=2551fb0c60d543edbcc09c97bcacdaca" target="_blank" style="font-weight: bold; color: #1CAAD9;"> Shell and Tube Heat Exchanger </a> by <a href="https://sketchfab.com/dubey.ujjwal1994?utm_medium=embed&utm_campaign=share-popup&utm_content=2551fb0c60d543edbcc09c97bcacdaca" target="_blank" style="font-weight: bold; color: #1CAAD9;"> dubey.ujjwal1994 </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=2551fb0c60d543edbcc09c97bcacdaca" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>
    <div class="sketchfab-embed-wrapper"> <iframe title="PLATE HEAT EXCHANGER" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="640" height="480" src="https://sketchfab.com/models/bdc3a20833e74482a6ad110bf59a5636/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/plate-heat-exchanger-bdc3a20833e74482a6ad110bf59a5636?utm_medium=embed&utm_campaign=share-popup&utm_content=bdc3a20833e74482a6ad110bf59a5636" target="_blank" style="font-weight: bold; color: #1CAAD9;"> PLATE HEAT EXCHANGER </a> by <a href="https://sketchfab.com/dubey.ujjwal1994?utm_medium=embed&utm_campaign=share-popup&utm_content=bdc3a20833e74482a6ad110bf59a5636" target="_blank" style="font-weight: bold; color: #1CAAD9;"> dubey.ujjwal1994 </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=bdc3a20833e74482a6ad110bf59a5636" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>
    <div class="sketchfab-embed-wrapper"> <iframe title="Heat Exchanger" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="640" height="480" src="https://sketchfab.com/models/dc2bc4cbe8704bc9a205fb12d3d98a77/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/heat-exchanger-dc2bc4cbe8704bc9a205fb12d3d98a77?utm_medium=embed&utm_campaign=share-popup&utm_content=dc2bc4cbe8704bc9a205fb12d3d98a77" target="_blank" style="font-weight: bold; color: #1CAAD9;"> Heat Exchanger </a> by <a href="https://sketchfab.com/3DDomino?utm_medium=embed&utm_campaign=share-popup&utm_content=dc2bc4cbe8704bc9a205fb12d3d98a77" target="_blank" style="font-weight: bold; color: #1CAAD9;"> 3DDomino </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=dc2bc4cbe8704bc9a205fb12d3d98a77" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>
  </el-row>
</template>

<script setup>


</script>

<style>
  #mysite{
    width: 100%;
    height: calc(100vh - 12px);
    frameborder:0;
  }
</style>